# c) Correr el siguiente código en un archivo nuevo y chequear que los resultados sean
# correctos:
# print(0, "al cubo:", elevarAlCubo(0))
# print(1, "al cubo:", elevarAlCubo(1))
# print(2, "al cubo:", elevarAlCubo(2))
# print(3, "al cubo:", elevarAlCubo(3))
# print(4, "al cubo:", elevarAlCubo(4))
# print(5, "al cubo:", elevarAlCubo(5))
# print(6, "al cubo:", elevarAlCubo(6))
# print(-1, "al cubo:", elevarAlCubo(-1))
# print(-2, "al cubo:", elevarAlCubo(-2))
# print(-3, "al cubo:", elevarAlCubo(-3))
# print(-4, "al cubo:", elevarAlCubo(-4))
# print(-5, "al cubo:", elevarAlCubo(-5))
from funcionCubo import *
print(0, "al cubo:", elevarAlCubo(0))
print(1, "al cubo:", elevarAlCubo(1))
print(2, "al cubo:", elevarAlCubo(2))
print(3, "al cubo:", elevarAlCubo(3))
print(4, "al cubo:", elevarAlCubo(4))
print(5, "al cubo:", elevarAlCubo(5))
print(6, "al cubo:", elevarAlCubo(6))
print(-1, "al cubo:", elevarAlCubo(-1))
print(-2, "al cubo:", elevarAlCubo(-2))
print(-3, "al cubo:", elevarAlCubo(-3))
print(-4, "al cubo:", elevarAlCubo(-4))
print(-5, "al cubo:", elevarAlCubo(-5))